
name: Deploy strapi (dev)

on:
  push:
    branches:
      - develop
    paths:
      - 'apps/strapi/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # deploy to Heroku
    - uses: akhileshns/heroku-deploy@v3.6.8
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_app_name: ${{ secrets.HEROKU_APP_NAME_DEV_STRAPI }}
        heroku_email: ${{ secrets.HEROKU_EMAIL }}
        branch: "develop"
