
name: Deploy client (prod)

on:
  push:
    branches:
      - master
    paths:
      - apps/client/**
      - libs/**

jobs:

  build-and-test:
    name: Install dependencies, build libs & test libs and client app
    # Set the type of machine to run on
    runs-on: ubuntu-latest
    strategy:
      # setup node version
      matrix:
        node-version: [12.x]
      
    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - uses: actions/checkout@v2

      # use correct node version
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      # cache node_modules
      - name: Cache node-modules
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      # install dependencies
      - name: Install packages
        run: yarn install --frozen-lockfile

      # build libs
      - run: yarn build:libs

      # test libs & client code
      - name: Test project
        run: yarn test:libs & yarn test:client
        env:
          CI: true

  # deploy to netlify
  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: publish to netlify
        run: curl -X POST -d {} ${{ secrets.NETLIFY_BUILD_HOOK_CLIENT_PROD }}
